/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvogadosRouteImport } from './routes/advogados'
import { Route as AreasRouteImport } from './routes/areas'
import { Route as AtualizacoesRouteImport } from './routes/atualizacoes'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as SobreRouteImport } from './routes/sobre'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvogadosRoute = AdvogadosRouteImport.update({
  id: '/advogados',
  path: '/advogados',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasRoute = AreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizacoesRoute = AtualizacoesRouteImport.update({
  id: '/atualizacoes',
  path: '/atualizacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advogados': typeof AdvogadosRoute
  '/areas': typeof AreasRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advogados': typeof AdvogadosRoute
  '/areas': typeof AreasRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advogados': typeof AdvogadosRoute
  '/areas': typeof AreasRoute
  '/atualizacoes': typeof AtualizacoesRoute
  '/contato': typeof ContatoRoute
  '/galeria': typeof GaleriaRoute
  '/noticias': typeof NoticiasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advogados'
    | '/areas'
    | '/atualizacoes'
    | '/contato'
    | '/galeria'
    | '/noticias'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advogados'
    | '/areas'
    | '/atualizacoes'
    | '/contato'
    | '/galeria'
    | '/noticias'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/advogados'
    | '/areas'
    | '/atualizacoes'
    | '/contato'
    | '/galeria'
    | '/noticias'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvogadosRoute: typeof AdvogadosRoute
  AreasRoute: typeof AreasRoute
  AtualizacoesRoute: typeof AtualizacoesRoute
  ContatoRoute: typeof ContatoRoute
  GaleriaRoute: typeof GaleriaRoute
  NoticiasRoute: typeof NoticiasRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advogados': {
      id: '/advogados'
      path: '/advogados'
      fullPath: '/advogados'
      preLoaderRoute: typeof AdvogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas': {
      id: '/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizacoes': {
      id: '/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AtualizacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvogadosRoute: AdvogadosRoute,
  AreasRoute: AreasRoute,
  AtualizacoesRoute: AtualizacoesRoute,
  ContatoRoute: ContatoRoute,
  GaleriaRoute: GaleriaRoute,
  NoticiasRoute: NoticiasRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
