export type Story = {
  id: number | string;
  slug?: string;
  title: string;
  summary: string;
  source: string;
  sourceUrl: string;
  publishedAt: string;
  tags: string[];
  sourceNote?: string;
};

export const filters = [
  "Todos",
  "Parauapebas",
  "Canaã dos Carajás",
  "Marabá",
  "Curionópolis",
  "Eldorado",
  "Belém / Pará",
  "Política",
  "Mineração",
  "Emprego",
  "Polícia",
  "Economia",
  "Agenda Regional",
  "Utilidade Pública",
];

export const sourceOrder = [
  "Zé Dudu",
  "Pebinha de Açúcar",
  "Portal Canaã",
  "Portal Parauapebas",
  "Correio de Carajás",
  "Portal Debate",
  "Gazeta Carajás",
  "Info30",
  "EldoNews",
  "O Liberal",
  "Diário do Pará",
  "Agência Pará",
  "G1 Pará",
];

export const stories: Story[] = [
  {
    id: 1,
    title: "Parauapebas amplia o acesso à saúde do homem com horário diferenciado",
    summary: "Unidades de saúde passam a reservar atendimento mensal das 15h às 21h, ampliando o acesso masculino a consultas e ações de prevenção.",
    source: "Zé Dudu",
    sourceUrl: "https://www.zedudu.com.br/parauapebas-amplia-o-acesso-a-saude-do-homem-com-horario-diferenciado-de-atendimento/",
    publishedAt: "9 jul 2026",
    tags: ["Parauapebas", "Utilidade Pública"],
  },
  {
    id: 2,
    title: "Parauapebas reúne especialistas para planejar a diversificação econômica",
    summary: "O Fórum Parauapebas 2040 reuniu poder público, setor produtivo e sociedade para discutir novas vocações econômicas e reduzir a dependência da mineração.",
    source: "Zé Dudu",
    sourceUrl: "https://www.zedudu.com.br/parauapebas-reune-especialistas-setor-produtivo-e-sociedade-para-construir-estrategias-de-diversificacao-economica/",
    publishedAt: "10 jul 2026",
    tags: ["Parauapebas", "Economia", "Mineração"],
  },
  {
    id: 3,
    title: "Canaã dos Carajás abre inscrições para a 10ª Feira de Negócios",
    summary: "A Fenecan terá 145 espaços para expositores e será realizada de 24 a 27 de setembro, com foco em negócios e empreendedorismo local.",
    source: "Zé Dudu",
    sourceUrl: "https://www.zedudu.com.br/canaa-dos-carajas-inscricoes-para-a-10a-feira-de-negocios-abrem-em-3-de-agosto/",
    publishedAt: "17 jul 2026",
    tags: ["Canaã dos Carajás", "Economia", "Agenda Regional"],
  },
  {
    id: 4,
    title: "Prefeitura de Parauapebas decreta recesso funcional",
    summary: "O município definiu período de recesso e informou as exceções para serviços essenciais, com retomada das atividades regulares no início de agosto.",
    source: "Zé Dudu",
    sourceUrl: "https://www.zedudu.com.br/prefeitura-de-parauapebas-decreta-recesso-funcional/",
    publishedAt: "20 jul 2026",
    tags: ["Parauapebas", "Utilidade Pública"],
  },
  {
    id: 5,
    title: "Águas do Pará apresenta avanços no saneamento do sul e sudeste paraense",
    summary: "O balanço de seis meses cita melhorias para mais de 450 mil moradores, incluindo Parauapebas, Canaã dos Carajás e municípios vizinhos.",
    source: "Zé Dudu",
    sourceUrl: "https://www.zedudu.com.br/seis-meses-de-operacao-aguas-do-para-avanca-no-saneamento-e-beneficia-mais-de-450-mil-moradores-no-sul-e-sudeste-do-para/",
    publishedAt: "jul 2026",
    tags: ["Parauapebas", "Canaã dos Carajás", "Utilidade Pública"],
  },

  {
    id: 6,
    title: "Rede municipal de Parauapebas inicia aulas para cerca de 49 mil estudantes",
    summary: "O ano letivo começou com aproximadamente 49 mil alunos e dois mil professores mobilizados na rede pública municipal.",
    source: "Pebinha de Açúcar",
    sourceUrl: "https://pebinhadeacucar.com.br/rede-municipal-de-parauapebas-inicia-aulas-nesta-quinta-para-aproximadamente-49-mil-estudantes/",
    publishedAt: "21 jan 2026",
    tags: ["Parauapebas", "Utilidade Pública"],
  },
  {
    id: 7,
    title: "Royalties de 2026 seguem abaixo do nível de 2024 em Parauapebas",
    summary: "Levantamento sobre a CFEM mostra arrecadação menor no início de 2026 e reforça o debate sobre receitas minerais e planejamento municipal.",
    source: "Pebinha de Açúcar",
    sourceUrl: "https://pebinhadeacucar.com.br/levantamento-mostra-que-royalties-de-2026-seguem-abaixo-do-nivel-de-2024-em-parauapebas/",
    publishedAt: "16 jan 2026",
    tags: ["Parauapebas", "Mineração", "Economia"],
  },
  {
    id: 8,
    title: "Vale abre vagas para jovem aprendiz em três cidades da região",
    summary: "O processo seletivo reúne oportunidades em Canaã dos Carajás, Curionópolis e Parauapebas, com inscrições realizadas pela internet.",
    source: "Pebinha de Açúcar",
    sourceUrl: "https://pebinhadeacucar.com.br/vale-abre-300-vagas-para-jovem-aprendiz-em-canaa-dos-carajas-curionopolis-e-parauapebas/",
    publishedAt: "30 jan 2026",
    tags: ["Canaã dos Carajás", "Curionópolis", "Parauapebas", "Emprego", "Mineração"],
  },
  {
    id: 9,
    title: "Parauapebas institui lei de transporte público gratuito",
    summary: "A legislação estabelece a implantação gradual da tarifa zero universal e coloca o município como pioneiro no Pará nesse modelo.",
    source: "Pebinha de Açúcar",
    sourceUrl: "https://pebinhadeacucar.com.br/parauapebas-se-torna-o-primeiro-municipio-do-para-a-instituir-lei-de-transporte-publico-gratuito/",
    publishedAt: "13 jan 2026",
    tags: ["Parauapebas", "Política", "Utilidade Pública"],
  },
  {
    id: 10,
    title: "Parauapebas debate o futuro econômico além da mineração",
    summary: "A Câmara endossou uma proposta de planejamento estratégico para preparar a transição econômica e ampliar alternativas de renda no município.",
    source: "Pebinha de Açúcar",
    sourceUrl: "https://pebinhadeacucar.com.br/parauapebas-debate-futuro-alem-da-mineracao-e-camara-endossa-proposta-de-planejamento-estrategico/",
    publishedAt: "19 fev 2026",
    tags: ["Parauapebas", "Política", "Economia", "Mineração"],
  },

  {
    id: 11,
    title: "Eugênio Gadelha inicia agenda eleitoral com comício em Canaã",
    summary: "O lançamento de campanha foi marcado para 21 de agosto, às 19h, na Avenida Teotônio Vilela, em Canaã dos Carajás.",
    source: "Portal Canaã",
    sourceUrl: "https://portalcanaa.com.br/para/eugenio-gadelha-inicia-corrida-eleitoral-com-grande-comicio-no-dia-21-de-agosto/",
    publishedAt: "14 ago 2026",
    tags: ["Canaã dos Carajás", "Política", "Agenda Regional"],
  },
  {
    id: 12,
    title: "Vale Base Metals antecipa novo projeto de cobre em Salobo",
    summary: "A companhia prevê iniciar em 2028 uma nova etapa de processamento que pode ampliar a capacidade e a produção anual de cobre em Marabá.",
    source: "Portal Canaã",
    sourceUrl: "https://portalcanaa.com.br/para/vale-base-metals-antecipa-novo-projeto-de-cobre-em-salobo-e-preve-operacao-para-2028/",
    publishedAt: "14 ago 2026",
    tags: ["Marabá", "Mineração", "Economia"],
  },
  {
    id: 13,
    title: "Programa de estágio técnico oferece cerca de 80 vagas no Pará",
    summary: "As oportunidades da Vale atendem Marabá, Parauapebas e Canaã dos Carajás, com inscrições abertas até 10 de setembro.",
    source: "Portal Canaã",
    sourceUrl: "https://portalcanaa.com.br/para/vale-abre-inscricoes-para-programa-de-estagio-tecnico-com-cerca-de-80-vagas-em-maraba-parauapebas-e-canaa-dos-carajas/",
    publishedAt: "14 ago 2026",
    tags: ["Marabá", "Parauapebas", "Canaã dos Carajás", "Emprego", "Mineração"],
  },
  {
    id: 14,
    title: "Academia do Peixe Frito é tema de programação gratuita em Belém",
    summary: "A iniciativa reúne aula pública e workshop nos dias 15 e 16 de agosto para valorizar um marco do modernismo amazônico.",
    source: "Portal Canaã",
    sourceUrl: "https://portalcanaa.com.br/para/academia-do-peixe-frito-marco-do-modernismo-amazonico-e-tema-de-aula-publica-e-workshop-em-belem/",
    publishedAt: "11 ago 2026",
    tags: ["Belém / Pará", "Agenda Regional"],
  },
  {
    id: 15,
    title: "Ações de empreendedorismo de Canaã ganham destaque em feira de Parauapebas",
    summary: "Iniciativas desenvolvidas em Canaã dos Carajás foram apresentadas durante a feira de negócios de Parauapebas, fortalecendo a integração regional.",
    source: "Portal Canaã",
    sourceUrl: "https://portalcanaa.com.br/para/acoes-de-empreendedorismo-em-canaa-sao-destaque-na-feira-de-negocios-de-parauapebas/",
    publishedAt: "10 ago 2026",
    tags: ["Canaã dos Carajás", "Parauapebas", "Economia", "Agenda Regional"],
  },

  {
    id: 16,
    title: "Vale abre programa de estágio técnico com mais de 450 vagas",
    summary: "A seleção nacional inclui oportunidades no Pará para estudantes de Marabá, Parauapebas e Canaã dos Carajás.",
    source: "Portal Parauapebas",
    sourceUrl: "https://portalparauapebas.com/vale-abre-inscricoes-para-programa-de-estagio-tecnico-com-mais-de-450-vagas-em-cinco-estados/",
    publishedAt: "ago 2026",
    tags: ["Marabá", "Parauapebas", "Canaã dos Carajás", "Emprego", "Mineração"],
  },
  {
    id: 17,
    title: "Operação Extractio II combate garimpo ilegal em Parauapebas",
    summary: "A ação de fiscalização mirou estruturas ligadas à extração clandestina e reforçou o combate a crimes ambientais no município.",
    source: "Portal Parauapebas",
    sourceUrl: "https://portalparauapebas.com/parauapebas-operacao-extractio-ii-combate-garimpo-ilegal-em-parauapebas/",
    publishedAt: "ago 2026",
    tags: ["Parauapebas", "Polícia", "Mineração"],
  },
  {
    id: 18,
    title: "Eugênio Gadelha lança campanha para deputado estadual em Canaã",
    summary: "O ato político de abertura da campanha terá comício em Canaã dos Carajás e participação de apoiadores da região.",
    source: "Portal Parauapebas",
    sourceUrl: "https://portalparauapebas.com/eugenio-gadelha-lanca-campanha-para-deputado-estadual-com-comicio-em-canaa-dos-carajas/",
    publishedAt: "ago 2026",
    tags: ["Canaã dos Carajás", "Política", "Agenda Regional"],
  },
  {
    id: 19,
    title: "ExpoCanaã entra na contagem regressiva",
    summary: "A programação agropecuária promete movimentar Canaã dos Carajás com negócios, entretenimento e atrações para o público regional.",
    source: "Portal Parauapebas",
    sourceUrl: "https://portalparauapebas.com/expocanaa-entra-na-contagem-regressiva-e-promete-movimentar-canaa-dos-carajas/",
    publishedAt: "ago 2026",
    tags: ["Canaã dos Carajás", "Economia", "Agenda Regional"],
  },
  {
    id: 20,
    title: "MPPA investiga impactos ambientais de data center de IA na Amazônia",
    summary: "O Ministério Público acompanha o licenciamento e os possíveis efeitos ambientais do primeiro grande data center voltado à inteligência artificial na região.",
    source: "Portal Parauapebas",
    sourceUrl: "https://portalparauapebas.com/mppa-investiga-impactos-ambientais-do-primeiro-data-center-de-ia-da-amazonia/",
    publishedAt: "ago 2026",
    tags: ["Belém / Pará", "Política", "Economia"],
  },

  {
    id: 21,
    title: "Incêndio destrói loja de roupas em Parauapebas",
    summary: "As chamas atingiram o estabelecimento neste sábado e foram controladas pelas equipes de emergência; não houve registro de feridos.",
    source: "Correio de Carajás",
    sourceUrl: "https://correiodecarajas.com.br/incendio-consome-loja-de-roupas-em-parauapebas-chamas-sao-controladas/",
    publishedAt: "15 ago 2026",
    tags: ["Parauapebas", "Utilidade Pública"],
  },
  {
    id: 22,
    title: "Condenado por tráfico de drogas é preso em Marabá",
    summary: "Uma ação policial cumpriu ordem judicial contra um homem condenado por tráfico, dando continuidade às operações de segurança na cidade.",
    source: "Correio de Carajás",
    sourceUrl: "https://correiodecarajas.com.br/condenado-por-trafico-de-drogas-e-preso-em-maraba/",
    publishedAt: "ago 2026",
    tags: ["Marabá", "Polícia"],
  },
  {
    id: 23,
    title: "Festival Búfalos Gourmet movimenta Parauapebas",
    summary: "O evento reúne gastronomia, cultura e empreendedorismo até 16 de agosto, com programação voltada ao público regional.",
    source: "Correio de Carajás",
    sourceUrl: "https://correiodecarajas.com.br/festival-bufalos-gourmet-alimenta-parauapebas/",
    publishedAt: "15 ago 2026",
    tags: ["Parauapebas", "Economia", "Agenda Regional"],
  },
  {
    id: 24,
    title: "Unifesspa oferece 20 vagas para mestrado em Computação",
    summary: "O programa sediado em Marabá recebe inscrições até 18 de agosto e amplia as oportunidades de formação tecnológica na região.",
    source: "Correio de Carajás",
    sourceUrl: "https://correiodecarajas.com.br/unifesspa-oferece-20-vagas-para-mestrado-em-computacao/",
    publishedAt: "15 ago 2026",
    tags: ["Marabá", "Emprego", "Utilidade Pública"],
  },
  {
    id: 25,
    title: "Marabá recebe programa de capacitação para empreendedores",
    summary: "A iniciativa oferece formação prática para quem já empreende ou planeja estruturar um novo negócio no município.",
    source: "Correio de Carajás",
    sourceUrl: "https://correiodecarajas.com.br/maraba-recebe-programa-que-capacita-empreendedores/",
    publishedAt: "ago 2026",
    tags: ["Marabá", "Economia", "Emprego"],
  },

  {
    id: 26,
    title: "Obras do Parque Maria Bonita avançam em Parauapebas",
    summary: "A gestão municipal vistoriou o projeto, que já ultrapassou metade da execução e deve ampliar as opções de lazer e convivência.",
    source: "Portal Debate",
    sourceUrl: "https://debatecarajas.com.br/prefeito-aurelio-goiano-acompanha-avanco-das-obras-do-parque-maria-bonita-em-parauapebas/",
    publishedAt: "13 ago 2026",
    tags: ["Parauapebas", "Política", "Utilidade Pública"],
  },
  {
    id: 27,
    title: "Segfaz alerta contribuintes sobre e-mail falso em Marabá",
    summary: "A secretaria municipal orienta a população a ignorar mensagens que apontam supostas irregularidades em alvarás e a confirmar cobranças pelos canais oficiais.",
    source: "Portal Debate",
    sourceUrl: "https://debatecarajas.com.br/maraba-segfaz-alerta-contribuintes-sobre-e-mail-falso-com-suposta-irregularidade-em-alvara/",
    publishedAt: "13 ago 2026",
    tags: ["Marabá", "Polícia", "Utilidade Pública"],
  },
  {
    id: 28,
    title: "Pavimentação chega à Travessa Goiás, no bairro Liberdade",
    summary: "A Prefeitura de Marabá avançou com a aplicação de asfalto na via, atendendo uma demanda de mobilidade dos moradores.",
    source: "Portal Debate",
    sourceUrl: "https://debatecarajas.com.br/prefeitura-de-maraba-avanca-com-pavimentacao-e-leva-asfalto-a-travessa-goias-no-bairro-liberdade/",
    publishedAt: "ago 2026",
    tags: ["Marabá", "Política", "Utilidade Pública"],
  },
  {
    id: 29,
    title: "Homem é morto na zona rural de Parauapebas e suspeito é preso",
    summary: "A Polícia prendeu um suspeito após um homicídio ocorrido na área rural do município; o caso segue sob investigação.",
    source: "Portal Debate",
    sourceUrl: "https://debatecarajas.com.br/homem-e-morto-a-facadas-na-zona-rural-de-parauapebas-suspeito-e-preso/",
    publishedAt: "13 ago 2026",
    tags: ["Parauapebas", "Polícia"],
  },
  {
    id: 30,
    title: "Marabá entrega novas instalações para atendimento e proteção à mulher",
    summary: "As estruturas do CEPPM e do CRAM foram renovadas para concentrar serviços de orientação, acolhimento e garantia de direitos.",
    source: "Portal Debate",
    sourceUrl: "https://debatecarajas.com.br/gestao-entrega-novas-instalacoes-para-ceppm-e-cram-em-maraba/",
    publishedAt: "ago 2026",
    tags: ["Marabá", "Política", "Utilidade Pública"],
  },

  {
    id: 31,
    title: "Vale abre 450 vagas de estágio em cidades da região e outros estados",
    summary: "A seleção inclui oportunidades em Canaã dos Carajás, Parauapebas e Marabá, além de unidades em outras localidades do país.",
    source: "Gazeta Carajás",
    sourceUrl: "https://www.gazetacarajas.com/noticia/vale-abre-450-vagas-para-estagio-em-canaa-parauapebas-maraba-sao-luis-e-muito-mais",
    publishedAt: "14 ago 2026",
    tags: ["Canaã dos Carajás", "Parauapebas", "Marabá", "Emprego", "Mineração"],
  },
  {
    id: 32,
    title: "Motociclista fica ferido na ponte rodoferroviária de Marabá",
    summary: "O condutor perdeu o controle da moto e recebeu atendimento do Samu após cair na ponte sobre o Rio Tocantins.",
    source: "Gazeta Carajás",
    sourceUrl: "https://www.gazetacarajas.com/noticia/motociclista-fica-ferido-apos-cair-de-moto-na-ponte-rodoferroviaria-de-maraba",
    publishedAt: "14 ago 2026",
    tags: ["Marabá", "Utilidade Pública"],
  },
  {
    id: 33,
    title: "Aeroporto de Marabá triplica terminal para ampliar capacidade",
    summary: "A expansão prevê terminal com mais de cinco mil metros quadrados e capacidade anual de 600 mil passageiros, reforçando o papel regional do aeroporto.",
    source: "Gazeta Carajás",
    sourceUrl: "https://www.gazetacarajas.com/noticia/aeroporto-de-maraba-triplica-terminal-para-manter-papel-estrategico-no-sudeste-do-para",
    publishedAt: "3 ago 2026",
    tags: ["Marabá", "Economia", "Utilidade Pública"],
  },
  {
    id: 34,
    title: "Exportações do Pará para os EUA caem no primeiro semestre",
    summary: "Dados apresentados pela Fiepa indicam recuo nas vendas para o mercado norte-americano e aumento das importações no mesmo período.",
    source: "Gazeta Carajás",
    sourceUrl: "https://www.gazetacarajas.com/noticia/exportacoes-do-para-para-os-eua-caem-30-no-1-semestre-de-2026-aponta-fiepa",
    publishedAt: "18 jul 2026",
    tags: ["Belém / Pará", "Economia", "Mineração"],
  },
  {
    id: 35,
    title: "Comício marca início da corrida eleitoral de Eugênio Gadelha",
    summary: "A agenda política foi anunciada para 21 de agosto, em Canaã dos Carajás, com concentração na Avenida Teotônio Vilela.",
    source: "Gazeta Carajás",
    sourceUrl: "https://www.gazetacarajas.com/noticia/eugenio-gadelha-inicia-corrida-eleitoral-com-grande-comicio-no-dia-21-de-agosto",
    publishedAt: "14 ago 2026",
    tags: ["Canaã dos Carajás", "Política", "Agenda Regional"],
  },

  {
    id: 36,
    title: "Pioneiro de Serra Pelada sofre queda grave e aguarda transferência",
    summary: "O morador caiu em uma fossa e foi estabilizado enquanto aguardava remoção para uma unidade de saúde em Marabá.",
    source: "Info30",
    sourceUrl: "https://info30.com.br/noticia/102/pioneiro-de-serra-pelada-sofre-grave-queda-em-fossa-e-aguarda-transferencia-para-maraba",
    publishedAt: "jul 2026",
    tags: ["Curionópolis", "Marabá", "Utilidade Pública"],
  },
  {
    id: 37,
    title: "Micro-ônibus cai em ribanceira entre Canaã e Parauapebas",
    summary: "O veículo saiu da pista com cerca de dez passageiros; equipes de resgate atenderam os feridos no trecho rodoviário.",
    source: "Info30",
    sourceUrl: "https://info30.com.br/noticia/99/micro-onibus-sai-da-pista-e-cai-em-ribanceira-entre-canaa-dos-carajas-e-parauapebas",
    publishedAt: "24 jul 2026",
    tags: ["Canaã dos Carajás", "Parauapebas", "Utilidade Pública"],
  },
  {
    id: 38,
    title: "Motociclista fica desacordado após acidente em Curionópolis",
    summary: "O condutor perdeu o controle da direção e recebeu socorro após um acidente grave registrado no município.",
    source: "Info30",
    sourceUrl: "https://info30.com.br/noticia/98/motociclista-perde-o-controle-da-direcao-e-fica-desacordado-apos-grave-acidente-em-curionopolis",
    publishedAt: "jul 2026",
    tags: ["Curionópolis", "Utilidade Pública"],
  },
  {
    id: 39,
    title: "Moradores contestam operação contra garimpo na Vila Sansão",
    summary: "Imagens dos danos após uma ação contra mineração ilegal provocaram reação de moradores da comunidade rural de Parauapebas.",
    source: "Info30",
    sourceUrl: "https://info30.com.br/noticia/96/novas-fotos-mostram-destruicao-apos-operacao-contra-garimpo-e-revoltam-moradores-da-vila-sansao-em-parauapebas",
    publishedAt: "jul 2026",
    tags: ["Parauapebas", "Mineração", "Polícia"],
  },
  {
    id: 40,
    title: "OAB alerta para mais de 44 mil processos parados em Marabá",
    summary: "A entidade denunciou acúmulo processual e cobrou medidas para melhorar a prestação do serviço judicial no município.",
    source: "Info30",
    sourceUrl: "https://info30.com.br/noticia/90/maraba-enfrenta-colapso-na-justica-com-mais-de-44-mil-processos-parados-denuncia-oab",
    publishedAt: "jul 2026",
    tags: ["Marabá", "Política", "Utilidade Pública"],
  },

  {
    id: 41,
    title: "Homem é morto e outro fica ferido em ataque",
    summary: "A ocorrência policial foi registrada em Mato Grosso do Sul e está incluída apenas como amostra do conteúdo atual publicado pelo EldoNews.",
    source: "EldoNews",
    sourceUrl: "https://www.eldonews.com.br/noticias/brasil/951508",
    publishedAt: "14 ago 2026",
    tags: ["Eldorado", "Polícia"],
    sourceNote: "Atenção: o EldoNews informado é de Eldorado, Mato Grosso do Sul — fora da região de Carajás.",
  },
  {
    id: 42,
    title: "Motorista morre em capotamento de carreta na BR-369",
    summary: "O acidente rodoviário ocorreu fora do Pará e integra a cobertura atual do portal EldoNews, sediado em Eldorado/MS.",
    source: "EldoNews",
    sourceUrl: "https://www.eldonews.com.br/noticias/brasil/951507",
    publishedAt: "14 ago 2026",
    tags: ["Eldorado", "Utilidade Pública"],
    sourceNote: "Atenção: o EldoNews informado é de Eldorado, Mato Grosso do Sul — fora da região de Carajás.",
  },
  {
    id: 43,
    title: "Morador de MS planeja expedição por 196 países",
    summary: "O projeto prevê uma viagem de três anos e meio pelas capitais de 196 países, partindo de Mato Grosso do Sul.",
    source: "EldoNews",
    sourceUrl: "https://www.eldonews.com.br/noticias/brasil/951506",
    publishedAt: "14 ago 2026",
    tags: ["Eldorado", "Agenda Regional"],
    sourceNote: "Atenção: o EldoNews informado é de Eldorado, Mato Grosso do Sul — fora da região de Carajás.",
  },
  {
    id: 44,
    title: "Idoso investigado por abuso tem prisão preventiva decretada",
    summary: "A Justiça decretou a prisão do investigado em um caso envolvendo menores; a ocorrência foi publicada na cobertura do EldoNews em MS.",
    source: "EldoNews",
    sourceUrl: "https://www.eldonews.com.br/noticias/brasil/951505",
    publishedAt: "14 ago 2026",
    tags: ["Eldorado", "Polícia"],
    sourceNote: "Atenção: o EldoNews informado é de Eldorado, Mato Grosso do Sul — fora da região de Carajás.",
  },
  {
    id: 45,
    title: "Brasil abre processo sobre Lei da Reciprocidade e notifica os EUA",
    summary: "O governo brasileiro iniciou o procedimento previsto na legislação de reciprocidade econômica e comunicou a diplomacia norte-americana.",
    source: "EldoNews",
    sourceUrl: "https://www.eldonews.com.br/noticias/brasil/951503",
    publishedAt: "14 ago 2026",
    tags: ["Eldorado", "Política", "Economia"],
    sourceNote: "Atenção: o EldoNews informado é de Eldorado, Mato Grosso do Sul — fora da região de Carajás.",
  },

  {
    id: 46,
    title: "Incêndio atinge e destrói loja em Parauapebas",
    summary: "O estabelecimento foi tomado pelas chamas neste sábado; o fogo foi controlado e não houve registro de pessoas feridas.",
    source: "O Liberal",
    sourceUrl: "https://www.oliberal.com/policia/incendio-atinge-loja-em-parauapebas-neste-sabado-e-destroi-estabelecimento-1.1157489",
    publishedAt: "15 ago 2026",
    tags: ["Parauapebas", "Utilidade Pública"],
  },
  {
    id: 47,
    title: "Lanches de rua mantêm clientela fiel e projetam alta em Belém",
    summary: "Empreendedores do setor relatam movimento constante e expectativa de crescimento nas vendas ao longo do segundo semestre.",
    source: "O Liberal",
    sourceUrl: "https://www.oliberal.com/economia/em-belem-lanches-de-rua-tem-clientes-fieis-eprojetam-alta-nas-vendas-neste-semestre-1.1157332",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Economia", "Emprego"],
  },
  {
    id: 48,
    title: "Petrobras anuncia descoberta de petróleo na Foz do Amazonas",
    summary: "A companhia confirmou indícios de petróleo durante a perfuração e informou que os trabalhos de avaliação continuam na margem equatorial.",
    source: "O Liberal",
    sourceUrl: "https://www.oliberal.com/economia/petrobras-descobre-petroleo-na-foz-do-amazonas-1.1157313",
    publishedAt: "14 ago 2026",
    tags: ["Belém / Pará", "Mineração", "Economia"],
  },
  {
    id: 49,
    title: "Preço do açaí recua em julho em Belém",
    summary: "Apesar da queda mensal, o açaí do tipo grosso ainda acumula alta em doze meses e segue pressionando o orçamento das famílias.",
    source: "O Liberal",
    sourceUrl: "https://www.oliberal.com/economia/preco-do-acai-recua-em-julho-em-belem-mas-tipo-grosso-ainda-acumula-alta-de-14-em-12-meses-1.1157011",
    publishedAt: "ago 2026",
    tags: ["Belém / Pará", "Economia", "Utilidade Pública"],
  },
  {
    id: 50,
    title: "Cavalo é atropelado na Avenida Centenário, em Belém",
    summary: "O animal recebeu atendimento após o acidente e o caso reacendeu o alerta sobre animais soltos em vias de grande circulação.",
    source: "O Liberal",
    sourceUrl: "https://www.oliberal.com/policia/cavalo-e-atropelado-na-avenida-centenario-em-belem-1.1157428",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Utilidade Pública"],
  },

  {
    id: 51,
    title: "Lugares de Belém preservam a história da Adesão do Pará",
    summary: "Um roteiro por prédios e espaços históricos ajuda a compreender os acontecimentos ligados ao 15 de Agosto na capital paraense.",
    source: "Diário do Pará",
    sourceUrl: "https://diariodopara.com.br/belem/15-de-agosto-conheca-os-lugares-de-belem-que-ainda-guardam-a-historia-da-adesao-do-para/",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Agenda Regional"],
  },
  {
    id: 52,
    title: "Mercado da beleza impulsiona lojas de cosméticos em Belém",
    summary: "O crescimento do setor amplia o movimento do comércio especializado e cria novas oportunidades para empreendedores na capital.",
    source: "Diário do Pará",
    sourceUrl: "https://diariodopara.com.br/belem/mercado-da-beleza-cresce-no-brasil-e-faz-lojas-de-cosmeticos-explodirem-em-belem/",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Economia", "Emprego"],
  },
  {
    id: 53,
    title: "Preço do açaí recua em Belém, mas ainda pesa no orçamento",
    summary: "O valor médio caiu no mês, porém permanece elevado para consumidores, especialmente nas categorias mais encorpadas do produto.",
    source: "Diário do Pará",
    sourceUrl: "https://diariodopara.com.br/belem/preco-do-acai-recua-em-belem-mas-ainda-pesa-no-orcamento/",
    publishedAt: "ago 2026",
    tags: ["Belém / Pará", "Economia", "Utilidade Pública"],
  },
  {
    id: 54,
    title: "Belém terá ônibus gratuitos durante todo o fim de semana",
    summary: "A gratuidade foi anunciada para os dias 15 e 16 de agosto, facilitando o deslocamento da população durante o feriado e a programação da cidade.",
    source: "Diário do Pará",
    sourceUrl: "https://diariodopara.com.br/belem/populacao-de-belem-tera-onibus-de-graca-em-todo-o-fim-de-semana/",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Utilidade Pública", "Agenda Regional"],
  },
  {
    id: 55,
    title: "Iphan Pará celebra o mês do patrimônio com programação especial",
    summary: "Atividades entre 17 e 20 de agosto promovem educação patrimonial, memória e valorização de bens culturais paraenses.",
    source: "Diário do Pará",
    sourceUrl: "https://diariodopara.com.br/belem/iphan-para-celebra-mes-do-patrimonio-com-programacao-especial/",
    publishedAt: "ago 2026",
    tags: ["Belém / Pará", "Agenda Regional", "Utilidade Pública"],
  },

  {
    id: 56,
    title: "Qualifica Pará já capacitou mais de 44 mil pessoas",
    summary: "O programa estadual apresenta balanço de cursos profissionalizantes realizados em diferentes municípios e voltados à inserção no mercado de trabalho.",
    source: "Agência Pará",
    sourceUrl: "https://www.agenciapara.com.br/noticia/78502/qualifica-para-ja-capacitou-mais-de-44-mil-pessoas-em-todo-para",
    publishedAt: "27 jun 2026",
    tags: ["Belém / Pará", "Emprego", "Política"],
    sourceNote: "O portal da Agência Pará está temporariamente suspenso em respeito à legislação eleitoral; o link original foi preservado.",
  },
  {
    id: 57,
    title: "Hospital Regional de Marabá e Policlínica Carajás integram rede de saúde",
    summary: "As unidades promoveram uma ação de alinhamento para melhorar fluxos de atendimento e fortalecer a assistência pública no sudeste do Pará.",
    source: "Agência Pará",
    sourceUrl: "https://www.agenciapara.com.br/noticia/78480/hospital-regional-de-maraba-e-policlinica-carajas-promovem-integracao-da-rede-publica-de-saude",
    publishedAt: "26 jun 2026",
    tags: ["Marabá", "Utilidade Pública", "Política"],
    sourceNote: "O portal da Agência Pará está temporariamente suspenso em respeito à legislação eleitoral; o link original foi preservado.",
  },
  {
    id: 58,
    title: "Rota Belém–Lisboa completa 12 anos de conexão internacional",
    summary: "A ligação aérea é apresentada como vetor de turismo, negócios e integração entre a Amazônia e a Europa.",
    source: "Agência Pará",
    sourceUrl: "https://www.agenciapara.com.br/noticia/78498/rota-belemlisboa-completa-12-anos-fortalecendo-a-conexao-entre-a-amazonia-e-a-europa",
    publishedAt: "26 jun 2026",
    tags: ["Belém / Pará", "Economia", "Agenda Regional"],
    sourceNote: "O portal da Agência Pará está temporariamente suspenso em respeito à legislação eleitoral; o link original foi preservado.",
  },
  {
    id: 59,
    title: "Secretaria de Justiça abre seleção para cargos de nível superior",
    summary: "O processo seletivo simplificado oferece oportunidades profissionais no serviço público estadual, conforme requisitos publicados no edital.",
    source: "Agência Pará",
    sourceUrl: "https://agenciapara.com.br/noticia/78258/secretaria-de-justica-abre-processo-seletivo-simplificado-para-cargos-de-nivel-superior",
    publishedAt: "19 jun 2026",
    tags: ["Belém / Pará", "Emprego", "Utilidade Pública"],
    sourceNote: "O portal da Agência Pará está temporariamente suspenso em respeito à legislação eleitoral; o link original foi preservado.",
  },
  {
    id: 60,
    title: "Hospital Materno Infantil de Marabá abre processo seletivo",
    summary: "A seleção busca profissionais para ampliar os serviços da unidade regional, com regras e etapas disponíveis no anúncio original.",
    source: "Agência Pará",
    sourceUrl: "https://agenciapara.com.br/noticia/77217/hospital-regional-materno-infantil-de-maraba-abre-processo-seletivo-para-ampliacao-dos-servicos",
    publishedAt: "15 mai 2026",
    tags: ["Marabá", "Emprego", "Utilidade Pública"],
    sourceNote: "O portal da Agência Pará está temporariamente suspenso em respeito à legislação eleitoral; o link original foi preservado.",
  },

  {
    id: 61,
    title: "Feriado da Adesão do Pará altera funcionamento em Belém",
    summary: "O guia reúne informações sobre serviços, comércio e equipamentos que abrem ou fecham na capital durante o feriado de 15 de agosto.",
    source: "G1 Pará",
    sourceUrl: "https://g1.globo.com/pa/para/noticia/2026/08/15/feriado-de-adesao-do-para-veja-o-que-abre-e-o-que-fecha-em-belem.ghtml",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Utilidade Pública"],
  },
  {
    id: 62,
    title: "Parque Zoobotânico do Museu Goeldi celebra 131 anos",
    summary: "A programação de aniversário oferece trilhas gratuitas e atividades educativas em Belém para aproximar o público da biodiversidade amazônica.",
    source: "G1 Pará",
    sourceUrl: "https://g1.globo.com/pa/para/noticia/2026/08/15/parque-zoobotanico-do-museu-goeldi-faz-131-anos-com-trilhas-gratuitas-em-belem.ghtml",
    publishedAt: "15 ago 2026",
    tags: ["Belém / Pará", "Agenda Regional", "Utilidade Pública"],
  },
  {
    id: 63,
    title: "Suspeito de matar professor em Belém é preso em Canaã",
    summary: "A Polícia localizou em Canaã dos Carajás um homem investigado por homicídio ocorrido na capital paraense.",
    source: "G1 Pará",
    sourceUrl: "https://g1.globo.com/pa/para/noticia/2026/08/14/suspeito-de-matar-professor-em-belem-e-preso-em-canaa-dos-carajas.ghtml",
    publishedAt: "14 ago 2026",
    tags: ["Canaã dos Carajás", "Belém / Pará", "Polícia"],
  },
  {
    id: 64,
    title: "Cursos, vagas e seleções: oportunidades de agosto no Pará",
    summary: "A relação concentra processos seletivos, cursos e oportunidades profissionais com inscrições abertas em diferentes cidades paraenses.",
    source: "G1 Pará",
    sourceUrl: "https://g1.globo.com/pa/para/noticia/2026/08/03/cursos-vagas-e-selecoes-veja-servicos-e-oportunidades-de-agosto-de-2026-no-para.ghtml",
    publishedAt: "3 ago 2026",
    tags: ["Belém / Pará", "Emprego", "Utilidade Pública"],
  },
  {
    id: 65,
    title: "Cidades do Pará recebem atendimento trabalhista gratuito",
    summary: "Uma ação itinerante do TRT-8 leva orientação e serviços da Justiça do Trabalho para municípios paraenses ao longo do mês.",
    source: "G1 Pará",
    sourceUrl: "https://g1.globo.com/pa/para/noticia/2026/08/04/cidades-do-pa-recebem-atendimento-trabalhista-gratuito-do-trt-8.ghtml",
    publishedAt: "4 ago 2026",
    tags: ["Belém / Pará", "Emprego", "Utilidade Pública"],
  },
];
